Adding rsa signing functions
RenaissanceBug/racket-jwt pull request #6
Opened 2020-09-16 21:54 UTC by themetaschemer

Extending this package to include 3 new signing functions: RS256, RS384 and RS512. 

I am using the pk-sign procedure provided by the crypto module. Had to tweak the signatures of the high-level interface to allow bytes for secrets.

2020-09-17 14:38 UTC, RenaissanceBug commented
Thanks! I'll review & respond within the next few days.

2020-12-03 04:50 UTC, themetaschemer commented
Hi, just checking in to see if you had a chance to review. Thanks.

2020-12-04 03:27 UTC, RenaissanceBug commented
Thanks for the nudge. Will look right now.

2020-12-04 03:53 UTC, RenaissanceBug requested changes
Looks good! thanks!

2020-12-04 03:53 UTC, RenaissanceBug commented on net/jwt/algorithms.rkt
> +         none hs256 hs384 hs512 rs256
```suggestion
         none hs256 hs384 hs512
```

2020-12-04 19:34 UTC, themetaschemer commented
Cool. Accepted the suggested change.

2020-12-04 19:40 UTC, merged

2020-12-04 19:42 UTC, RenaissanceBug commented
All done. Thanks again (for the changes, and your patience!).

2020-12-04 20:02 UTC, themetaschemer commented
Thanks! We've made using Racket a little bit better :)

2020-12-04 20:18 UTC, RenaissanceBug commented
Yay!

BTW, this library started as an offshoot of a web project that I’ve long since abandoned, and (now coming back from a 2-year sabbatical from coding) I don’t have a strong sense of what functionality is important to implement next. If you have encountered other wants as a user of it, please let me know.

Thanks again.

> On Dec 4, 2020, at 12:02, TheMetaSchemer <notifications@github.com> wrote:
> 
> ﻿
> Thanks! We've made using Racket a little bit better :)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-04 20:24 UTC, themetaschemer commented
Yes, will definitely do that. I actually started using this library to implement authentication for Google's cloud services. I picked up another abandoned google cloud api project and updated it to use their modern jwt based auth for service accounts. I ultimate goal would be to evolve this library into a full Google cloud services api library using the machine-readable api spec that Google has. But your jwt library is the foundation for the auth in it!
A. 
    On Friday, December 4, 2020, 12:18:30 PM PST, Jordan Johnson <notifications@github.com> wrote:  
 
 

Yay!

BTW, this library started as an offshoot of a web project that I’ve long since abandoned, and (now coming back from a 2-year sabbatical from coding) I don’t have a strong sense of what functionality is important to implement next. If you have encountered other wants as a user of it, please let me know.

Thanks again.

> On Dec 4, 2020, at 12:02, TheMetaSchemer <notifications@github.com> wrote:
> 
> ﻿
> Thanks! We've made using Racket a little bit better :)
> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

2020-12-05 03:03 UTC, RenaissanceBug commented
Oh, that’s fantastic! It was the need for authentication that prompted me to start working on the lib, so I’m delighted that the actual auth machinery is now getting built on top of it. 😁

> On Dec 4, 2020, at 12:25, TheMetaSchemer <notifications@github.com> wrote:
> 
> ﻿
> Yes, will definitely do that. I actually started using this library to implement authentication for Google's cloud services. I picked up another abandoned google cloud api project and updated it to use their modern jwt based auth for service accounts. I ultimate goal would be to evolve this library into a full Google cloud services api library using the machine-readable api spec that Google has. But your jwt library is the foundation for the auth in it!
> A. 
> On Friday, December 4, 2020, 12:18:30 PM PST, Jordan Johnson <notifications@github.com> wrote: 
> 
> 
> 
> Yay!
> 
> BTW, this library started as an offshoot of a web project that I’ve long since abandoned, and (now coming back from a 2-year sabbatical from coding) I don’t have a strong sense of what functionality is important to implement next. If you have encountered other wants as a user of it, please let me know.
> 
> Thanks again.
> 
> > On Dec 4, 2020, at 12:02, TheMetaSchemer <notifications@github.com> wrote:
> > 
> > ﻿
> > Thanks! We've made using Racket a little bit better :)
> > 
> > —
> > You are receiving this because you modified the open/close state.
> > Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub, or unsubscribe.